// This file is automatically generated by Firebase Studio.
// Do not edit this file manually, as your changes will be overwritten.

// Your web app's Firebase configuration
// For Firebase JS SDK v7.20.0 and later, measurementId is optional
export const firebaseConfig = {
  "projectId": "studio-8007541695-b958e",
  "appId": "1:1031762743213:web:33ce8ca17c45073e88db24",
  "apiKey": "AIzaSyBN7sSxTg-ZNuS_iJ_CGdwt4inb911C9dw",
  "authDomain": "studio-8007541695-b958e.firebaseapp.com",
  "measurementId": "",
  "messagingSenderId": "1031762743213"
};
